### ISSUE TITLE
Production fails if a composite is removed (e.g. due to solar angle limit)

### ISSUE THREAD

**Issue by pnuu** [pytroll/trollflow-sat#13]
If a composite is removed due to e.g. solar angle limit, the production will crash. The reason is that the filenames are created based on the config, not the actually existing datasets. Log shown below.

> Traceback (most recent call last):
>   File "/usr/lib64/python2.7/threading.py", line 813, in __bootstrap_inner
>     self.run()
>   File "/usr/lib64/python2.7/threading.py", line 766, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/home/users/xtuser/current/lib/python2.7/site-packages/trollflow_sat-0.8.0-py2.7.egg/trollflow_sat/satpy_writer.py", line 182, in run **kwargs)
>   File "/home/users/xtuser/current/lib/python2.7/site-packages/satpy-0.7.3-py2.7.egg/satpy/scene.py", line 622, in save_dataset
>     writer.save_dataset(self[dataset_id],
>   File "/home/users/xtuser/current/lib/python2.7/site-packages/satpy-0.7.3-py2.7.egg/satpy/scene.py", line 303, in __getitem__
>     return self.datasets[key]
>   File "/home/users/xtuser/current/lib/python2.7/site-packages/satpy-0.7.3-py2.7.egg/satpy/readers/__init__.py", line 182, in __getitem__
>     raise KeyError("No dataset matching '{}' found".format(str(item)))
> KeyError: "No dataset matching 'snow_age' found"`

**Comment by pnuu** [comment]
fixed by #14
